=== NTNU-sondrbaa-2019/DB-O6/Disney.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<!-- 2019 Sondre Benjamin Aasen -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Disney">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Actors">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Actor" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Name" type="xs:string"/>
                                        <xs:element name="BirthDay" type="xs:date"/>
                                        <xs:element name="BirthPlace">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="[a-zA-Z ]+(, [a-zA-Z ]+)+"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                    <xs:unique name="UniqueActor">
                        <xs:selector xpath="Actor"/>
                        <xs:field xpath="@id"/>
                    </xs:unique>
                    <xs:key name="ActorIDs">
                        <xs:selector xpath="Actor"/>
                        <xs:field xpath="@id"/>
                    </xs:key>
                </xs:element>
                <xs:element name="Subsidiaries">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Subsidiary" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Movie" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Name">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute name="lang">
                                                                        <xs:simpleType>
                                                                            <xs:restriction base="xs:string">
                                                                                <xs:length value="2"/>
                                                                            </xs:restriction>
                                                                        </xs:simpleType>
                                                                    </xs:attribute>
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="Year" type="xs:gYear"/>
                                                    <xs:element name="ScreenTime" minOccurs="0" maxOccurs="1">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:positiveInteger">
                                                                    <xs:attribute name="unit">
                                                                        <xs:simpleType>
                                                                            <xs:restriction base="xs:string">
                                                                                <xs:enumeration value="minutes"/>
                                                                                <xs:enumeration value="seconds"/>
                                                                            </xs:restriction>
                                                                        </xs:simpleType>
                                                                    </xs:attribute>
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="Cast" minOccurs="0" maxOccurs="1">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="Role" maxOccurs="unbounded">
                                                                    <xs:complexType>
                                                                        <xs:attribute name="name" type="xs:string" use="required"/>
                                                                        <xs:attribute name="alias" type="xs:string" use="optional"/>
                                                                        <xs:attribute name="actor" type="xs:string" use="required"/>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                        <xs:keyref name="ActorRefer" refer="ActorIDs">
                                                            <xs:selector xpath="Role"/>
                                                            <xs:field xpath="@actor"/>
                                                        </xs:keyref>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:string" use="required"/>
                                </xs:complexType>
                                <xs:unique name="UniqueMovie">
                                    <xs:selector xpath="Movie"/>
                                    <xs:field xpath="Name"/>
                                    <xs:field xpath="Year"/>
                                </xs:unique>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                    <xs:unique name="UniqueSubsidiary">
                        <xs:selector xpath="Subsidiary"/>
                        <xs:field xpath="@id"/>
                    </xs:unique>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== NTNU-sondrbaa-2019/DB-O6/DisneyNoActorName.xml
<?xml version="1.0" encoding="UTF-8"?>

<Disney xmlns:xsi= "http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation="Disney.xsd">

  <Actors>
    <Actor id="RobertDowneyJr">
      <Name>Robert Downey Jr.</Name>
      <BirthDay>1965-04-04</BirthDay>
      <BirthPlace>Manhattan, New York City, New York, USA</BirthPlace>
    </Actor>
  </Actors>

  <Subsidiaries>

    <Subsidiary id="MarvelStudios">
      <Movie>
        <Name lang="en">Iron Man</Name>
        <Year>2008</Year>
        <ScreenTime unit="minutes">126</ScreenTime>
        <Cast>
          <Role alias="Iron Man" actor="RobertDowneyJr" />
        </Cast>
      </Movie>
    </Subsidiary>

  </Subsidiaries>

</Disney>
